import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-green-400 mt-8 ml-0 text-8xl flex flex-row">
        draftdigital
      </h1>
      <h1 className="text-blue-400 ml-0 text-base">
        a supercool blockchain company
        <p className="text-4xl">
          made with 💙 by MG
        </p>
      </h1>
    </div>
  );
}
